const PLAYER_STORAGE_KEY='grassstatory.players';
const SETTINGS_STORAGE_KEY='grassstatory.settings';
const MATCH_STORAGE_KEY='grassstatory.matches';
const UPCOMING_STORAGE_KEY='grassstatory.fixtures';
const defaultSettings={matchFormat:5,playersOnPitch:5,teamName:'Your Team',teamAbbr:'YTM',ageGroup:'',season:'2026/27',primaryColor:'#25df72',secondaryColor:'#0b2a38',userRole:'Parent',planPreview:'free'};
let activeMatchId=null,timerInterval=null,statsFilter='All',adjustOurIds=new Set(),adjustOpponentCount=5,batchOffIds=new Set(),batchOnIds=new Set();
const $=id=>document.getElementById(id);
const views={homeView:$('homeView'),matchesView:$('matchesView'),statsView:$('statsView'),settingsView:$('settingsView'),platinumView:$('platinumView'),matchSetupView:$('matchSetupView'),liveMatchView:$('liveMatchView'),matchReportView:$('matchReportView'),onboardingView:$('onboardingView')};
const makeId=()=>crypto.randomUUID?crypto.randomUUID():`id-${Date.now()}-${Math.random().toString(16).slice(2)}`;
function loadJson(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function saveJson(k,v){localStorage.setItem(k,JSON.stringify(v))}
function loadPlayers(){return loadJson(PLAYER_STORAGE_KEY,[])}
function savePlayers(v){saveJson(PLAYER_STORAGE_KEY,v)}
function loadSettings(){return {...defaultSettings,...loadJson(SETTINGS_STORAGE_KEY,{})}}
function saveSettings(v){saveJson(SETTINGS_STORAGE_KEY,v)}
function loadMatches(){return loadJson(MATCH_STORAGE_KEY,[])}
function saveMatches(v){saveJson(MATCH_STORAGE_KEY,v)}
function loadFixtures(){return loadJson(UPCOMING_STORAGE_KEY,[])}
function saveFixtures(v){saveJson(UPCOMING_STORAGE_KEY,v)}
function escapeHtml(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function cleanAbbr(v,f='TEAM'){const x=String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'');return(x||f).slice(0,3)}
function derivedAbbr(name,f='OPP'){const w=String(name||'').trim().split(/\s+/).filter(Boolean);if(!w.length)return f;const c=w.join('').replace(/[^A-Za-z0-9]/g,'');if(c.length<=3)return c.toUpperCase();return cleanAbbr(w.map(x=>x[0]).join(''),f)}
function teamDisplay(){const s=loadSettings();return{name:s.teamName||'Your Team',abbr:cleanAbbr(s.teamAbbr,'YTM')}}
function playerLabel(p){return`${p.number?`#${p.number} `:''}${p.name}${p.position?` · ${p.position}`:''}`}
function formatDate(v){if(!v)return'Unknown date';return new Date(`${v}T00:00:00`).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
function periodLabel(p){return p===1?'1H':'2H'}
function showView(view){Object.values(views).forEach(v=>v?.classList.add('hidden'));view?.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});if(view===views.homeView)renderHome();if(view===views.matchesView)renderMatchesView();if(view===views.statsView)renderStatsView();if(view===views.settingsView)renderSettings();}
function updatePlanRadios(){document.querySelectorAll('[name="planPreview"]').forEach(r=>{r.checked=loadSettings().planPreview===r.value})}
function refreshIdentity(){const t=teamDisplay();for(const [id,val] of [['homeTeamCrest',t.abbr],['settingsTeamCrest',t.abbr],['onboardingTeamCrest',cleanAbbr($('onboardingTeamAbbr')?.value,t.abbr)]])if($(id))$(id).textContent=val;if($('homeTeamName'))$('homeTeamName').textContent=t.name}
function renderSettings(){const s=loadSettings();if($('teamName'))$('teamName').value=s.teamName||'Your Team';if($('teamAbbr'))$('teamAbbr').value=cleanAbbr(s.teamAbbr,'YTM');if($('matchFormat'))$('matchFormat').value=String(s.matchFormat);if($('playersOnPitch'))$('playersOnPitch').value=s.playersOnPitch;if($('ageGroup'))$('ageGroup').value=s.ageGroup||'';if($('season'))$('season').value=s.season||'2026/27';if($('primaryColor'))$('primaryColor').value=s.primaryColor||'#25df72';if($('secondaryColor'))$('secondaryColor').value=s.secondaryColor||'#0b2a38';const sq=$('squadSize');if(sq?.closest('label'))sq.closest('label').style.display='none';updatePlanRadios();renderPlayers();refreshIdentity()}
function renderPlayers(){const ps=loadPlayers(),s=loadSettings();if($('squadCount'))$('squadCount').textContent=`${ps.length} players`;if(!$('playerList'))return;$('playerList').innerHTML=ps.length?[...ps].sort((a,b)=>(Number(a.number)||999)-(Number(b.number)||999)).map(p=>`<button class="player-row" type="button" data-edit-player="${p.id}"><span class="player-number">${escapeHtml(p.number||'-')}</span><span class="player-name">${escapeHtml(p.name)}</span><span class="position-badge">${escapeHtml(p.position||'—')}</span><span class="edit-label">Edit</span></button>`).join(''):'<p class="muted">No players yet.</p>';document.querySelectorAll('[data-edit-player]').forEach(b=>b.onclick=()=>openEditPlayer(b.dataset.editPlayer));}
let editingPlayerId=null;
function openPlayerDialog(id=null){editingPlayerId=id;const p=id&&loadPlayers().find(x=>x.id===id);$('playerDialogTitle').textContent=p?'Edit player':'Add player';$('playerName').value=p?.name||'';$('playerNumber').value=p?.number||'';$('playerPosition').value=p?.position||'';$('deletePlayerBtn').classList.toggle('hidden',!p);$('playerDialog').showModal();$('playerName').focus()}
const openEditPlayer=id=>openPlayerDialog(id);
function renderHome(){refreshIdentity();renderSeasonSummary();renderMatchHistory();}
function renderSeasonSummary(){const matches=loadMatches().filter(m=>m.status==='completed'||m.fullTime),premium=loadSettings().planPreview==='platinum';let wins=0,draws=0,losses=0,gf=0,ga=0;matches.forEach(m=>{gf+=m.ourScore||0;ga+=m.theirScore||0;if(m.ourScore>m.theirScore)wins++;else if(m.ourScore<m.theirScore)losses++;else draws++});const cards=`<div class="stat-card"><strong>${matches.length}</strong><span>Matches recorded</span></div>`+(premium?`<div class="stat-card"><strong>${wins}</strong><span>Won</span></div><div class="stat-card"><strong>${draws}</strong><span>Drawn</span></div><div class="stat-card"><strong>${losses}</strong><span>Lost</span></div><div class="stat-card"><strong>${gf}</strong><span>Goals</span></div><div class="stat-card"><strong>${ga}</strong><span>Against</span></div>`:'');$('seasonSummary').innerHTML=cards;if(!matches.length){$('playerStatsTable').innerHTML='<p class="muted stats-empty">Complete a match and your football record will appear here.</p>';return}const stats=getPlayerStats('All');if(!premium){$('playerStatsTable').innerHTML=`<div class="free-stats-card"><div class="free-stats-head"><strong>Goalscorers</strong><span>Free</span></div>${stats.rows.filter(p=>p.goals>0).map(p=>`<div class="free-goal-row"><strong>${escapeHtml(p.name)}</strong><span>⚽ ${p.goals}</span></div>`).join('')||'<p class="muted">No goals recorded yet.</p>'}<div class="upgrade-preview"><strong>🔒 Unlock your complete GrassStatory</strong><span>Appearances · assists · minutes · form · milestones · competition stats</span><button type="button" class="primary-btn" id="homeUpgradeBtn">Explore Platinum</button></div></div>`;$('homeUpgradeBtn').onclick=()=>showView(views.platinumView)}else renderPlayerCards(stats.rows)}
function renderPlayerCards(rows){$('playerStatsTable').innerHTML=`<div class="player-stats-list">${rows.map(p=>`<article class="player-stat-card"><button class="player-stat-head player-stat-toggle" type="button" aria-expanded="false"><div class="player-stat-shirt">${escapeHtml(p.number||'–')}</div><div class="player-stat-identity"><strong>${escapeHtml(p.name)}</strong>${p.position?`<span>${escapeHtml(p.position)}</span>`:''}</div><div class="player-stat-mini"><span><strong>${p.apps}</strong> Apps</span><span><strong>${p.starts}</strong> Starts</span><span class="mini-goal"><strong>${p.goals}</strong> Goals</span><span class="mini-assist"><strong>${p.assists}</strong> Assists</span></div><span class="player-stat-chevron">⌄</span></button><div class="player-stat-details" hidden><div class="player-stat-grid"><div><strong>${p.apps}</strong><span>Apps</span></div><div><strong>${p.starts}</strong><span>Starts</span></div><div><strong>${p.subApps}</strong><span>Subs</span></div><div><strong>${p.minutes}</strong><span>Minutes</span></div><div class="stat-accent-goal"><strong>${p.goals}</strong><span>Goals</span></div><div class="stat-accent-assist"><strong>${p.assists}</strong><span>Assists</span></div></div></div></article>`).join('')}</div>`;document.querySelectorAll('.player-stat-toggle').forEach(btn=>btn.onclick=()=>{const d=btn.closest('.player-stat-card').querySelector('.player-stat-details'),exp=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!exp));d.hidden=exp;btn.closest('.player-stat-card').classList.toggle('is-expanded',!exp)})}
function getPlayerStats(filter){const matches=loadMatches().filter(m=>(m.status==='completed'||m.fullTime)&& (filter==='All'||(m.competition||'League')===filter));const ps=loadPlayers();const out={};ps.forEach(p=>out[p.id]={id:p.id,name:p.name,number:p.number||'',position:p.position||'',apps:0,starts:0,subApps:0,minutes:0,goals:0,assists:0});for(const m of matches){const starters=new Set(m.starterPlayerIds||[]),participants=new Set(starters);for(const e of m.events||[]){if(e.type==='substitution'&&e.onId)participants.add(e.onId);if(e.type==='players_adjust_our'&&e.playerId)participants.add(e.playerId);if(e.type==='our_goal'&&e.playerId&&e.goalType!=='own_goal'&&out[e.playerId])out[e.playerId].goals++;if(e.type==='our_goal'&&e.assistPlayerId&&e.goalType!=='own_goal'&&out[e.assistPlayerId])out[e.assistPlayerId].assists++}participants.forEach(id=>{if(out[id]){out[id].apps++;if(starters.has(id))out[id].starts++;else out[id].subApps++}});const mins=computeMinutes(m);Object.entries(mins).forEach(([id,s])=>{if(out[id])out[id].minutes+=Math.round(s/60)})}return{rows:Object.values(out).sort((a,b)=>b.goals-a.goals||b.apps-a.apps||(Number(a.number)||999)-(Number(b.number)||999),matches)}}
function computeMinutes(match){const byPeriod={1:0,2:0};if(match.periodDurations){byPeriod[1]=match.periodDurations[1]||0;byPeriod[2]=match.periodDurations[2]||0}else{byPeriod[1]=match.halfTimeScore?((match.period===2?match.halfTimeElapsedSeconds:match.periodElapsedSeconds)||0):(match.periodElapsedSeconds||0);byPeriod[2]=match.period===2?match.periodElapsedSeconds||0:0}const totals={};const events=match.events||[];let active=new Set(match.starterPlayerIds||[]);let currentPeriod=1,last=0;const add=(ids,sec)=>ids.forEach(id=>totals[id]=(totals[id]||0)+Math.max(0,sec));for(const e of events){if(e.period!==currentPeriod){add(active,Math.max(0,byPeriod[currentPeriod]-last));currentPeriod=e.period;last=0}const t=Number(e.seconds??((e.minute||1)-1)*60);add(active,t-last);last=t;if(e.type==='substitution'){if(e.offId)active.delete(e.offId);if(e.onId)active.add(e.onId)}else if(e.type==='players_adjust_our'){if(e.direction==='on')active.add(e.playerId);else active.delete(e.playerId)}}add(active,Math.max(0,byPeriod[currentPeriod]-last));return totals}
function renderMatchHistory(){const matches=loadMatches().filter(m=>m.status==='completed'||m.fullTime).sort((a,b)=>(b.completedAt||b.createdAt||'').localeCompare(a.completedAt||a.createdAt||''));$('matchHistoryList').innerHTML=matches.length?matches.map(m=>`<button class="history-card" type="button" data-history-match="${m.id}"><span class="history-date">${formatDate(m.date)}</span><span class="history-main"><span class="history-opponent">${escapeHtml(m.teamAbbr||teamDisplay().abbr)} ${m.ourScore} - ${m.theirScore} ${escapeHtml(m.opponentAbbr||derivedAbbr(m.opponent))}</span><br><span class="history-result">${m.competition||'League'} · ${escapeHtml(m.opponent)}</span></span><span>›</span></button>`).join(''):'<p class="muted">No completed matches yet.</p>';document.querySelectorAll('[data-history-match]').forEach(b=>b.onclick=()=>openMatchReport(b.dataset.historyMatch))}
function renderMatchesView(){const fx=loadFixtures();$('upcomingMatchesList').innerHTML=fx.length?fx.map(f=>`<div class="history-card"><span class="history-date">${formatDate(f.date)}</span><span class="history-main"><span class="history-opponent">${escapeHtml(teamDisplay().name)} vs ${escapeHtml(f.opponent)}</span><br><span class="history-result">${f.competition||'League'} · ${f.venue==='away'?'Away':'Home'}</span></span></div>`).join(''):'<p class="muted">No upcoming fixtures.</p>';$('matchesResultsList').innerHTML=$('matchHistoryList').innerHTML;document.querySelectorAll('#matchesResultsList [data-history-match]').forEach(b=>b.onclick=()=>openMatchReport(b.dataset.historyMatch))}
function renderStatsView(){const premium=loadSettings().planPreview==='platinum';const stats=getPlayerStats(statsFilter),team=getTeamStats(statsFilter);if(!premium){$('statsViewBody').innerHTML=`<div class="free-stats-card"><h3>${stats.matches.length} matches recorded</h3>${stats.rows.filter(p=>p.goals>0).map(p=>`<div class="free-goal-row"><strong>${escapeHtml(p.name)}</strong><span>⚽ ${p.goals}</span></div>`).join('')||'<p class="muted">No goals recorded yet.</p>'}<div class="upgrade-preview"><strong>🔒 Full statistics are a Platinum feature</strong><span>Team results · player appearances · minutes · assists · competition filters · milestones</span><button class="primary-btn" id="statsUpgradeInline" type="button">Explore Platinum</button></div></div>`;$('statsUpgradeInline')?.addEventListener('click',()=>showView(views.platinumView));return}$('statsViewBody').innerHTML=`<div class="stat-cards"><div class="stat-card"><strong>${team.played}</strong><span>Played</span></div><div class="stat-card"><strong>${team.won}</strong><span>Won</span></div><div class="stat-card"><strong>${team.drawn}</strong><span>Drawn</span></div><div class="stat-card"><strong>${team.lost}</strong><span>Lost</span></div><div class="stat-card"><strong>${team.gf}</strong><span>Goals For</span></div><div class="stat-card"><strong>${team.ga}</strong><span>Against</span></div></div><h3>Players</h3><div class="player-stats-list">${stats.rows.map(p=>`<article class="player-stat-card"><button class="player-stat-head player-stat-toggle" type="button" aria-expanded="false"><div class="player-stat-shirt">${escapeHtml(p.number||'–')}</div><div class="player-stat-identity"><strong>${escapeHtml(p.name)}</strong>${p.position?`<span>${escapeHtml(p.position)}</span>`:''}</div><div class="player-stat-mini"><span><strong>${p.apps}</strong> Apps</span><span><strong>${p.starts}</strong> Starts</span><span class="mini-goal"><strong>${p.goals}</strong> Goals</span><span class="mini-assist"><strong>${p.assists}</strong> Assists</span></div><span class="player-stat-chevron">⌄</span></button><div class="player-stat-details" hidden><div class="player-stat-grid"><div><strong>${p.apps}</strong><span>Apps</span></div><div><strong>${p.starts}</strong><span>Starts</span></div><div><strong>${p.subApps}</strong><span>Subs</span></div><div><strong>${p.minutes}</strong><span>Minutes</span></div><div class="stat-accent-goal"><strong>${p.goals}</strong><span>Goals</span></div><div class="stat-accent-assist"><strong>${p.assists}</strong><span>Assists</span></div></div></div></article>`).join('')}</div>`;document.querySelectorAll('#statsViewBody .player-stat-toggle').forEach(btn=>btn.onclick=()=>{const d=btn.closest('.player-stat-card').querySelector('.player-stat-details'),exp=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!exp));d.hidden=exp;btn.closest('.player-stat-card').classList.toggle('is-expanded',!exp)})}
function getTeamStats(filter){const ms=loadMatches().filter(m=>(m.status==='completed'||m.fullTime)&&(filter==='All'||(m.competition||'League')===filter));let won=0,drawn=0,lost=0,gf=0,ga=0;ms.forEach(m=>{gf+=m.ourScore||0;ga+=m.theirScore||0;if(m.ourScore>m.theirScore)won++;else if(m.ourScore<m.theirScore)lost++;else drawn++});return{played:ms.length,won,drawn,lost,gf,ga}}
function openMatchSetup(){const ps=loadPlayers(),s=loadSettings();if(ps.length<s.playersOnPitch){alert(`Add at least ${s.playersOnPitch} players first.`);return}window._available=new Set(ps.map(p=>p.id));window._starters=new Set(lastStartingIds());$('matchDate').value=new Date().toISOString().slice(0,10);$('opponentName').value='';$('opponentAbbr').value='';if($('matchCompetition'))$('matchCompetition').value='League';$('matchSetupError').textContent='';renderMatchSelection();showView(views.matchSetupView);renderMilestoneWatch()}
function lastStartingIds(){const ps=new Set(loadPlayers().map(p=>p.id));const last=loadMatches().filter(m=>m.status==='completed'||m.fullTime).sort((a,b)=>(b.completedAt||b.createdAt||'').localeCompare(a.completedAt||a.createdAt||''))[0];const ids=(last?.starterPlayerIds||[]).filter(id=>ps.has(id));const n=loadSettings().playersOnPitch;return ids.length===n?ids:loadPlayers().slice(0,n).map(p=>p.id)}
function renderMatchSelection(){const ps=loadPlayers(),s=loadSettings();$('lobbyFormatText').textContent=`${s.matchFormat}v${s.matchFormat}`;$('startingTeamHeading').textContent=`Starting ${s.playersOnPitch}`;$('availableCount').textContent=`${window._available.size} available`;$('starterCount').textContent=`${window._starters.size} / ${s.playersOnPitch}`;$('availabilityList').innerHTML=ps.map(p=>`<label class="selection-row"><input type="checkbox" class="availability-check" data-id="${p.id}" ${window._available.has(p.id)?'checked':''}><span>${escapeHtml(playerLabel(p))}</span></label>`).join('');$('starterList').innerHTML=ps.filter(p=>window._available.has(p.id)).map(p=>`<label class="selection-row ${window._starters.has(p.id)?'selected':''}"><input type="checkbox" class="starter-check" data-id="${p.id}" ${window._starters.has(p.id)?'checked':''}><span>${escapeHtml(playerLabel(p))}</span></label>`).join('');$('substituteList').innerHTML=ps.filter(p=>window._available.has(p.id)&&!window._starters.has(p.id)).map(p=>`<div class="summary-row">${escapeHtml(playerLabel(p))}</div>`).join('')||'<p class="muted">No substitutes selected.</p>';document.querySelectorAll('.availability-check').forEach(c=>c.onchange=()=>{if(c.checked)window._available.add(c.dataset.id);else{window._available.delete(c.dataset.id);window._starters.delete(c.dataset.id)}renderMatchSelection()});document.querySelectorAll('.starter-check').forEach(c=>c.onchange=()=>{if(c.checked){if(window._starters.size>=s.playersOnPitch){c.checked=false;return}window._starters.add(c.dataset.id)}else window._starters.delete(c.dataset.id);renderMatchSelection()})}
function currentMatch(){return loadMatches().find(m=>m.id===activeMatchId)||null}
function saveCurrent(m){const ms=loadMatches(),i=ms.findIndex(x=>x.id===m.id);if(i>=0){ms[i]=m;saveMatches(ms)}}
function ensureMatch(m){if(!Array.isArray(m.events))m.events=[];if(!Array.isArray(m.currentOnPitch))m.currentOnPitch=[...(m.starterPlayerIds||[])];if(!Array.isArray(m.currentSubs))m.currentSubs=[...(m.substitutePlayerIds||[])];if(!m.period)m.period=1;if(typeof m.halfTime!=='boolean')m.halfTime=false;if(typeof m.fullTime!=='boolean')m.fullTime=m.status==='completed';if(typeof m.periodElapsedSeconds!=='number')m.periodElapsedSeconds=0;if(!m.periodDurations)m.periodDurations={};if(typeof m.opponentPlayersOnPitch!=='number')m.opponentPlayersOnPitch=loadSettings().playersOnPitch;if(!m.competition)m.competition='League';return m}
function openLive(id){activeMatchId=id;const m=ensureMatch(currentMatch());m.periodStartedAt=null;saveCurrent(m);renderLive();showView(views.liveMatchView)}
function elapsedNow(){const m=currentMatch();if(!m)return 0;return(m.periodElapsedSeconds||0)+(m.periodStartedAt?Math.floor((Date.now()-m.periodStartedAt)/1000):0)}
function matchMinute(){return Math.floor(elapsedNow()/60)+1}
function updateClock(){const m=currentMatch();if(!$('matchClock')||!m)return;$('matchClock').textContent=`${String(Math.floor(elapsedNow()/60)).padStart(2,'0')}:${String(elapsedNow()%60).padStart(2,'0')}`;$('clockStatus').textContent=m.periodStartedAt?'Running':'Paused'}
function startTimer(){const m=currentMatch();if(!m||m.fullTime||m.halfTime||m.periodStartedAt)return;m.periodStartedAt=Date.now();saveCurrent(m);stopTimer();timerInterval=setInterval(updateClock,250);renderLive()}
function pauseTimer(){const m=currentMatch();if(!m||!m.periodStartedAt)return;m.periodElapsedSeconds=elapsedNow();m.periodStartedAt=null;saveCurrent(m);stopTimer();updateClock()}
function stopTimer(){if(timerInterval){clearInterval(timerInterval);timerInterval=null}}
function renderLive(){const m=ensureMatch(currentMatch());if(!m)return;const t=teamDisplay();$('ourScore').textContent=m.ourScore;$('theirScore').textContent=m.theirScore;$('ourTeamName').textContent=m.teamName||t.name;$('ourTeamCrest').textContent=cleanAbbr(m.teamAbbr,t.abbr);$('opponentScoreName').textContent=m.opponent;$('opponentTeamCrest').textContent=cleanAbbr(m.opponentAbbr,derivedAbbr(m.opponent));$('liveMeta').textContent=`${m.opponent} · ${m.venue==='home'?'Home':'Away'} · ${m.competition}`;$('livePlayerCount').textContent=`${m.currentOnPitch.length}v${m.opponentPlayersOnPitch}`;$('matchPeriod').textContent=m.period===1?'1st half':'2nd half';$('periodLabel').textContent=m.fullTime?'Full Time':(m.halfTime?'Half Time':(m.period===1?'1st Half':'2nd Half'));$('timerBtn').textContent=m.periodStartedAt?'Pause':'Start';$('timerBtn').disabled=m.fullTime||m.halfTime;$('halfTimeBtn').classList.toggle('hidden',m.period!==1||m.halfTime||m.fullTime);$('startSecondHalfBtn').classList.toggle('hidden',!(m.period===1&&m.halfTime&&!m.fullTime));$('fullTimeBtn').classList.toggle('hidden',!(m.period===2&&!m.fullTime));$('liveStarters').innerHTML=renderOurOnPitch(m);$('liveSubs').innerHTML=renderOurSubs(m);$('playersOnPitchStatus').textContent=`${m.currentOnPitch.length} v ${m.opponentPlayersOnPitch} · both sides can be adjusted.`;$('eventTimeline').innerHTML=m.events.length?[...m.events].reverse().map(e=>`<div class="event-row"><span class="event-minute">${periodLabel(e.period)} ${e.minute}'</span><span>${escapeHtml(eventText(e))}</span></div>`).join(''):'<p class="muted">No events yet.</p>';$('undoBtn').disabled=!m.events.length;updateClock();saveCurrent(m)}
function renderOurOnPitch(m){const by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));return m.currentOnPitch.map(id=>by[id]).filter(Boolean).map(p=>`<div class="summary-row">${escapeHtml(playerLabel(p))}</div>`).join('')||'<p class="muted">No players on pitch.</p>'}
function renderOurSubs(m){const by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));return m.currentSubs.map(id=>by[id]).filter(Boolean).map(p=>`<div class="summary-row">${escapeHtml(playerLabel(p))}</div>`).join('')||'<p class="muted">No substitutes.</p>'}
function eventText(e){const m=currentMatch(); const by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));if(e.type==='our_goal'){const gt=e.goalType==='penalty'?' (Penalty)':e.goalType==='own_goal'?' (Opposition Own Goal)':'';return`⚽ ${e.playerId&&by[e.playerId]?playerLabel(by[e.playerId]):'Opposition Own Goal'}${e.assistPlayerId&&by[e.assistPlayerId]?` — Assist: ${playerLabel(by[e.assistPlayerId])}`:''}${gt}`}if(e.type==='their_goal'){const gt=e.goalType==='penalty'?' (Penalty)':e.goalType==='own_goal'?' (Our Own Goal)':'';return`⚽ ${e.ownGoalPlayerId&&by[e.ownGoalPlayerId]?`${playerLabel(by[e.ownGoalPlayerId])} own goal`:m?.opponent||'Opponent'}${gt}`}if(e.type==='substitution')return`🔄 ${by[e.offId]?playerLabel(by[e.offId]):'Unknown'} off → ${by[e.onId]?playerLabel(by[e.onId]):'Unknown'} on`;if(e.type==='players_adjust_our')return`👥 ${by[e.playerId]?playerLabel(by[e.playerId]):'Player'} ${e.direction==='on'?'on':'off'} · ${e.newCount} on pitch`;if(e.type==='players_adjust_opponent')return`👥 Opponent now ${e.newCount} on pitch`;return e.type}
function eventState(m){return{currentOnPitch:[...(m.currentOnPitch||[])],currentSubs:[...(m.currentSubs||[])],opponentPlayersOnPitch:Number(m.opponentPlayersOnPitch)}}
function restoreState(m,s){m.currentOnPitch=[...(s.currentOnPitch||[])];m.currentSubs=[...(s.currentSubs||[])];m.opponentPlayersOnPitch=Number(s.opponentPlayersOnPitch)||loadSettings().playersOnPitch}
function recordGoal(kind,goalType,playerId,assistId,ownGoalPlayerId){const m=ensureMatch(currentMatch());if(!m||m.halfTime||m.fullTime)return;m.periodElapsedSeconds=elapsedNow();if(m.periodStartedAt)m.periodStartedAt=Date.now();const e={id:makeId(),type:kind,period:m.period,seconds:elapsedNow(),minute:matchMinute(),goalType,playerId:playerId||null,assistPlayerId:assistId||null,ownGoalPlayerId:ownGoalPlayerId||null,beforeScore:{our:m.ourScore,their:m.theirScore},beforeState:eventState(m)};m.events.push(e);if(kind==='our_goal')m.ourScore++;else m.theirScore++;saveCurrent(m);renderLive()}
function openGoalDialog(kind){const m=currentMatch();if(!m||m.halfTime||m.fullTime)return;const our=kind==='our_goal';$('goalDialogTitle').textContent=our?'Our Goal':'Opponent Goal';$('goalPlayerSection').classList.toggle('hidden',!our);$('goalType').value='normal';$('ownGoalPlayerWrap').classList.add('hidden');const by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));if(our){const on=m.currentOnPitch.map(id=>by[id]).filter(Boolean);$('goalScorer').innerHTML=on.map(p=>`<option value="${p.id}">${escapeHtml(playerLabel(p))}</option>`).join('');$('goalAssist').innerHTML='<option value="">No Assist</option>'+on.map(p=>`<option value="${p.id}">${escapeHtml(playerLabel(p))}</option>`).join('');$('ownGoalPlayer').innerHTML='<option value="">Not specified</option>'+on.map(p=>`<option value="${p.id}">${escapeHtml(playerLabel(p))}</option>`).join('')}else{$('ownGoalPlayer').innerHTML='<option value="">Not specified</option>'+m.currentOnPitch.map(id=>by[id]).filter(Boolean).map(p=>`<option value="${p.id}">${escapeHtml(playerLabel(p))}</option>`).join('')}$('goalDialog').dataset.kind=kind;$('goalDialog').showModal()}
function openSubDialog(){const m=currentMatch();if(!m||m.halfTime||m.fullTime)return;if(!m.currentSubs.length){alert('There are no substitutes available.');return}batchOffIds=new Set();batchOnIds=new Set();renderBatchSubs();$('subDialog').showModal()}
function renderBatchSubs(){const m=currentMatch(),by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));$('subOffList').innerHTML=m.currentOnPitch.map(id=>by[id]).filter(Boolean).map(p=>`<label class="batch-choice"><input type="checkbox" class="batch-off-check" data-id="${p.id}" ${batchOffIds.has(p.id)?'checked':''}><span>${escapeHtml(playerLabel(p))}</span></label>`).join('');$('subOnList').innerHTML=m.currentSubs.map(id=>by[id]).filter(Boolean).map(p=>`<label class="batch-choice"><input type="checkbox" class="batch-on-check" data-id="${p.id}" ${batchOnIds.has(p.id)?'checked':''}><span>${escapeHtml(playerLabel(p))}</span></label>`).join('');$('subOffCount').textContent=batchOffIds.size;$('subOnCount').textContent=batchOnIds.size;const valid=batchOffIds.size>0&&batchOffIds.size===batchOnIds.size;$('saveBatchSubsBtn').disabled=!valid;$('saveBatchSubsBtn').textContent=valid?`Save ${batchOffIds.size} substitution${batchOffIds.size===1?'':'s'}`:'Save substitutions';document.querySelectorAll('.batch-off-check').forEach(c=>c.onchange=()=>{c.checked?batchOffIds.add(c.dataset.id):batchOffIds.delete(c.dataset.id);renderBatchSubs()});document.querySelectorAll('.batch-on-check').forEach(c=>c.onchange=()=>{c.checked?batchOnIds.add(c.dataset.id):batchOnIds.delete(c.dataset.id);renderBatchSubs()})}
function saveBatchSubs(){const m=currentMatch();if(!m||!batchOffIds.size||batchOffIds.size!==batchOnIds.size)return;const before=eventState(m),offs=[...batchOffIds],ons=[...batchOnIds],sec=elapsedNow(),min=matchMinute();offs.forEach((off,i)=>{const on=ons[i];const ev={id:makeId(),type:'substitution',period:m.period,seconds:sec,minute:min,offId:off,onId:on,beforeState:eventState(m)};m.currentOnPitch=m.currentOnPitch.filter(id=>id!==off);m.currentOnPitch.push(on);m.currentSubs=m.currentSubs.filter(id=>id!==on);m.currentSubs.push(off);m.events.push(ev)});saveCurrent(m);$('subDialog').close();renderLive()}
function openAdjust(){const m=currentMatch();if(!m||m.halfTime||m.fullTime)return;adjustOurIds=new Set(m.currentOnPitch);adjustOpponentCount=m.opponentPlayersOnPitch;renderAdjust();$('adjustPlayersDialog').showModal()}
function renderAdjust(){const m=currentMatch(),by=Object.fromEntries(loadPlayers().map(p=>[p.id,p]));$('adjustOurTeamName').textContent=m.teamName||teamDisplay().name;$('adjustOpponentName').textContent=m.opponent;$('adjustOurCount').textContent=adjustOurIds.size;$('adjustOpponentCount').textContent=adjustOpponentCount;$('oppCountValue').textContent=adjustOpponentCount;$('adjustOurOnList').innerHTML=loadPlayers().filter(p=>adjustOurIds.has(p.id)).map(p=>`<label class="adjust-choice"><input type="checkbox" class="adjust-on" data-id="${p.id}" checked><span>${escapeHtml(playerLabel(p))}</span></label>`).join('');$('adjustOurOffList').innerHTML=loadPlayers().filter(p=>!adjustOurIds.has(p.id)).map(p=>`<label class="adjust-choice"><input type="checkbox" class="adjust-off" data-id="${p.id}"><span>${escapeHtml(playerLabel(p))}</span></label>`).join('');document.querySelectorAll('.adjust-on').forEach(c=>c.onchange=()=>{if(!c.checked)adjustOurIds.delete(c.dataset.id);renderAdjust()});document.querySelectorAll('.adjust-off').forEach(c=>c.onchange=()=>{if(c.checked)adjustOurIds.add(c.dataset.id);renderAdjust()});$('adjustPlayersHint').textContent=`Current match state: ${adjustOurIds.size} v ${adjustOpponentCount}.`}
function saveAdjust(){const m=currentMatch();if(!m)return;const before=eventState(m),sec=elapsedNow(),min=matchMinute(),old=new Set(m.currentOnPitch),next=new Set(adjustOurIds);for(const id of next)if(!old.has(id))m.events.push({id:makeId(),type:'players_adjust_our',period:m.period,seconds:sec,minute:min,playerId:id,direction:'on',newCount:next.size,beforeState:before});for(const id of old)if(!next.has(id))m.events.push({id:makeId(),type:'players_adjust_our',period:m.period,seconds:sec,minute:min,playerId:id,direction:'off',newCount:next.size,beforeState:before});if(m.opponentPlayersOnPitch!==adjustOpponentCount)m.events.push({id:makeId(),type:'players_adjust_opponent',period:m.period,seconds:sec,minute:min,newCount:adjustOpponentCount,beforeState:before});m.currentOnPitch=[...next];m.currentSubs=loadPlayers().map(p=>p.id).filter(id=>m.availablePlayerIds.includes(id)&&!next.has(id));m.opponentPlayersOnPitch=adjustOpponentCount;saveCurrent(m);$('adjustPlayersDialog').close();renderLive()}
function goalTypeChanged(){const type=$('goalType').value;$('ownGoalPlayerWrap').classList.toggle('hidden',type!=='own_goal');$('goalPlayerSection').querySelectorAll('select').forEach(x=>x.disabled=type==='own_goal')}
function undoLast(){const m=currentMatch();if(!m?.events.length)return;const e=m.events.pop();if(e.beforeState)restoreState(m,e.beforeState);if(e.beforeScore){m.ourScore=e.beforeScore.our;m.theirScore=e.beforeScore.their}saveCurrent(m);renderLive()}
function halfTime(){const m=currentMatch();if(!m||m.period!==1||m.fullTime)return;pauseTimer();m.halfTime=true;m.periodDurations[1]=m.periodElapsedSeconds;m.halfTimeElapsedSeconds=m.periodElapsedSeconds;m.halfTimeScore={our:m.ourScore,their:m.theirScore};saveCurrent(m);renderLive()}
function startSecond(){const m=currentMatch();if(!m||!m.halfTime||m.fullTime)return;m.period=2;m.halfTime=false;m.periodElapsedSeconds=0;m.periodStartedAt=null;saveCurrent(m);renderLive();startTimer()}
function fullTime(){const m=currentMatch();if(!m||m.period!==2||m.fullTime)return;pauseTimer();m.periodDurations[2]=m.periodElapsedSeconds;m.fullTime=true;m.status='completed';m.finalScore={our:m.ourScore,their:m.theirScore};m.completedAt=new Date().toISOString();saveCurrent(m);openMatchReport(m.id)}
function openMatchReport(id){const m=loadMatches().find(x=>x.id===id);if(!m)return;window._report=m;currentMatchReport=m;$('reportOurName').textContent=m.teamName||teamDisplay().name;$('reportOpponent').textContent=m.opponent;$('reportOurCrest').textContent=cleanAbbr(m.teamAbbr,teamDisplay().abbr);$('reportOpponentCrest').textContent=cleanAbbr(m.opponentAbbr,derivedAbbr(m.opponent));$('reportMeta').textContent=`${formatDate(m.date)} · ${m.venue==='home'?'Home':'Away'}`;$('reportCompetition').textContent=m.competition||'League';$('reportOurScore').textContent=m.ourScore;$('reportTheirScore').textContent=m.theirScore;$('reportHalfScore').textContent=`${m.halfTimeScore?.our??0} - ${m.halfTimeScore?.their??0}`;const goals=(m.events||[]).filter(e=>e.type==='our_goal'||e.type==='their_goal');const premium=loadSettings().planPreview==='platinum';$('reportOurScorers').innerHTML=scorerSummary(m,'our_goal',premium);$('reportTheirScorers').innerHTML=scorerSummary(m,'their_goal',premium);const assists=goals.filter(e=>e.type==='our_goal'&&e.assistPlayerId&&e.goalType!=='own_goal').map(e=>{const p=loadPlayers().find(x=>x.id===e.assistPlayerId);return p?`${p.name} (${periodLabel(e.period)} ${e.minute}')`:''}).filter(Boolean);$('reportAssistSummary').classList.toggle('hidden',!assists.length);if(assists.length)$('reportAssistSummary').innerHTML=`<strong>Assists</strong> · ${escapeHtml(assists.join(', '))}`;$('reportGoals').innerHTML=goals.map(e=>`<div class="event-row"><span class="event-minute">${periodLabel(e.period)} ${e.minute}'</span><span>${escapeHtml(eventText(e))}</span></div>`).join('')||'<p class="muted">No goals recorded.</p>';const other=(m.events||[]).filter(e=>e.type==='substitution'||e.type==='players_adjust_our'||e.type==='players_adjust_opponent');$('reportSubs').innerHTML=other.map(e=>`<div class="event-row"><span class="event-minute">${periodLabel(e.period)} ${e.minute}'</span><span>${escapeHtml(eventText(e))}</span></div>`).join('')||'<p class="muted">No player changes recorded.</p>';$('reportStarters').innerHTML=(m.starterPlayerIds||[]).map(id=>loadPlayers().find(p=>p.id===id)).filter(Boolean).map(p=>`<div class="summary-row">${escapeHtml(playerLabel(p))}</div>`).join('')||'<p class="muted">No starters recorded.</p>';$('reportSubstitutes').innerHTML=(m.substitutePlayerIds||[]).map(id=>loadPlayers().find(p=>p.id===id)).filter(Boolean).map(p=>`<div class="summary-row">${escapeHtml(playerLabel(p))}</div>`).join('')||'<p class="muted">No substitutes recorded.</p>';const premiumReport=loadSettings().planPreview==='platinum';$('toggleMatchDetailsBtn').classList.toggle('hidden',!premiumReport);$('reportDetailsPanel').classList.toggle('hidden',!premiumReport);$('reportAssistSummary').classList.toggle('hidden',!premiumReport||!assists.length);renderReportMilestones(m);showView(views.matchReportView)}
let currentMatchReport=null;
function scorerSummary(m,type,premium=false){const by=Object.fromEntries(loadPlayers().map(p=>[p.id,p])),gs=(m.events||[]).filter(e=>e.type===type&&e.goalType!=='own_goal'),groups=new Map();for(const e of gs){const key=type==='their_goal'?'opp':e.playerId;if(!groups.has(key))groups.set(key,{name:type==='their_goal'?m.opponent:(by[e.playerId]?.name||'Unknown'),times:[]});groups.get(key).times.push(`${periodLabel(e.period)} ${e.minute}'`)}return[...groups.values()].map(g=>`<div class="scorer-group"><strong>${escapeHtml(g.name)}</strong><span>${premium?escapeHtml(g.times.join(' · ')):''}</span></div>`).join('')||'<span class="muted">No goals</span>'}
refreshIdentity();wire();renderHome();renderSettings();if(!loadSettings().onboardingComplete)openOnboarding();
